# Generated by Django 4.0.1 on 2022-01-09 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
