# Generated by Django 4.0.1 on 2022-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0002_alter_temperaturereading_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='value_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
