# Generated by Django 4.0.1 on 2022-01-09 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0003_alter_temperaturereading_value_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='value_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
