# Generated by Django 4.0.1 on 2022-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0004_alter_temperaturereading_value_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='mode',
            field=models.FloatField(null=True),
        ),
    ]
