# Generated by Django 4.0.1 on 2022-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0005_temperaturereading_mean_temperaturereading_median_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='mode',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
