# Generated by Django 4.0.1 on 2022-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0006_alter_temperaturereading_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='std_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='variance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
