# Generated by Django 4.0.1 on 2022-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0007_temperaturereading_std_deviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='percentile25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='percentile50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='percentile75',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
