# Generated by Django 4.0.1 on 2022-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0010_alter_temperaturereading_mean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='mean',
            field=models.FloatField(null=True),
        ),
    ]
