# Generated by Django 4.0.1 on 2022-01-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_readings', '0011_alter_temperaturereading_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
